MVCMusicStoree/Controllers/ShoppingCartController.cs
using MVCMusicStoree.Models;
using MVCMusicStoree.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCMusicStoree.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
           
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            return View(viewModel);
        }
        
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums.Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedAlbum);
           
            return RedirectToAction("Index");
        }
        
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts.Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) + " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
         
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }


    }
}

MVCMusicStoree/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCMusicStoree.Models;

namespace MVCMusicStoree.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        // GET: Store
        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();
           
            return View(genres);
        }

        //GET: Store/Browse?genre=[some-genre]
        public ActionResult Browse(string genre)
        {

            var genreModel = storeDB.Genres.Include("Albums").Single(g => g.Name == genre);
            return View(genreModel);
        }

        //GET: Store/Details
        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);

            return View(album);
        }

        // GET: /Store/GenreMenu
        //This attribute will prevent the controller action from being executed by browsing to /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();
            return PartialView(genres);
        }
    }
}

MVCMusicStoree/Views/Store/Browse.cshtml
@model MVCMusicStoree.Models.Genre

@{
    ViewBag.Title = "Browse";
}

<h2>Browsing Genre: @Model.Name</h2>

<div class="genre">
    <h3><em>@Model.Name</em></h3>

    <ul id="album-list">
        @foreach(var album in Model.Albums)
        {
            <li>
                <a href="@Url.Action("Details", new { id = album.AlbumId })">
                    <img alt="@album.Title" src="@album.AlbumArtUrl" />
                    <span>@album.Title</span>
                </a>
            </li>
        }
    </ul>
</div>

MVCMusicStoree/Views/Store/Details.cshtml
@model MVCMusicStoree.Models.Album

@{
    ViewBag.Title = "Album - " + Model.Title;
}
<h2>@Model.Title</h2>
<p>
    <img alt="@Model.Title"
         src="@Model.AlbumArtUrl" />
</p>
<div id="album-details">
    <p>
        <em>Genre:</em>
        @Model.Genre.Name
    </p>
    <p>
        <em>Artist:</em>
        @Model.Artist.Name
    </p>
    <p>
        <em>Price:</em>
        @String.Format("{0:F}", Model.Price)
    </p>
    <p class="button">
        @Html.ActionLink("Add to cart", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, "")
    </p>
</div>

MVCMusicStoree/Views/Store/GenreMenu.cshtml
@model IEnumerable<MVCMusicStoree.Models.Genre>

<ul id="categories">
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name, "Browse", "Store", new { Genre = genre.Name }, null)
    </li>
    }
</ul>

MVCMusicStoree/Views/Store/Index.cshtml
@model IEnumerable<MVCMusicStoree.Models.Genre>

@{
    ViewBag.Title = "Store";
}

<h3>Browse Genres</h3>

<p>
    Select from @Model.Count() genres:
</p>

<ul>
    @foreach (var genre in Model)
    {
        <li>
            @Html.ActionLink(genre.Name, "Browse", new { genre = genre.Name })
        </li>
    }
</ul>